######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 14 09:59:19 2011
######################################################################

QT       += core gui opengl
TEMPLATE = app
TARGET =
DEPENDPATH += . src

# Input
HEADERS += src/glimageviewer.h src/mainwindow.h
FORMS += src/mainwindow.ui
SOURCES += src/glimageviewer.cpp src/main.cpp src/mainwindow.cpp
